"""remove_date_columns_from_flights

Revision ID: b1204c277bc3
Revises: 6516f98a06d8
Create Date: 2025-11-09 18:18:35.165048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1204c277bc3'
down_revision = '6516f98a06d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'arrival_date')
    op.drop_column('flights', 'departure_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('departure_date', sa.DATE(), nullable=False, comment='出发日期'))
    op.add_column('flights', sa.Column('arrival_date', sa.DATE(), nullable=False, comment='到达日期'))
    # ### end Alembic commands ###
